    name: Start Loop Scrape

    on: [push]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v2
          - name: Setup Python 3.10 (CPython)
            uses: actions/setup-python@v2
            with:
              python-version: 3.10
          - name: Main Execution
            env:
              DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              MENTION_USERS: ${{ secrets.MENTION_USERS }}
              MENTION_USERS_SECOND: ${{ secrets.MENTION_USERS_SECOND }}

            run: |
              pip install discum discord-webhook requests
              python scrapper.pyc
          - name: Loop Execution
            env:
              DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              MENTION_USERS: ${{ secrets.MENTION_USERS }}
              MENTION_USERS_SECOND: ${{ secrets.MENTION_USERS_SECOND }}
            run: |
              python scrapper.pyc
          - name: 2nd Loop Execution
            env:
              DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              MENTION_USERS: ${{ secrets.MENTION_USERS }}
              MENTION_USERS_SECOND: ${{ secrets.MENTION_USERS_SECOND }}
            run: |
              python scrapper.pyc
          - name: 3rd Loop Execution
            env:
              DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              MENTION_USERS: ${{ secrets.MENTION_USERS }}
              MENTION_USERS_SECOND: ${{ secrets.MENTION_USERS_SECOND }}
            run: |
              python scrapper.pyc
          - name: 4th Loop Execution
            env:
              DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              MENTION_USERS: ${{ secrets.MENTION_USERS }}
              MENTION_USERS_SECOND: ${{ secrets.MENTION_USERS_SECOND }}
            run: |
              python scrapper.pyc
          - name: Last Loop Execution
            env:
              DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
              MENTION_USERS: ${{ secrets.MENTION_USERS }}
              MENTION_USERS_SECOND: ${{ secrets.MENTION_USERS_SECOND }}
            run: |
              python scrapper.pyc
